# Generated by Django 2.1.5 on 2019-02-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architekt_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstandsflaechenplan', models.FileField(null=True, upload_to='plan_pdf/')),
                ('ansichten_plan', models.FileField(null=True, upload_to='plan_pdf')),
                ('freiflaechenplan', models.FileField(null=True, upload_to='plan_pdf')),
                ('statik_plan', models.FileField(null=True, upload_to='plan_pdf')),
                ('brandschutzkonzept', models.FileField(null=True, upload_to='plan_pdf')),
                ('energieausweis', models.FileField(null=True, upload_to='plan_pdf')),
            ],
        ),
        migrations.CreateModel(
            name='aufzug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('aufzug', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aussenanlagern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('terrassenbelaege', models.TextField(null=True)),
                ('pflanzen', models.TextField(null=True)),
                ('pflaster', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aussenputz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('aussenputz', models.TextField(null=True)),
                ('sockel', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bodenbelaege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('treppenhaus', models.TextField(null=True)),
                ('tiefgarage', models.TextField(null=True)),
                ('bad', models.TextField(null=True)),
                ('kueche', models.TextField(null=True)),
                ('flur', models.TextField(null=True)),
                ('wohnzimmer', models.TextField(null=True)),
                ('gaeste_wc', models.TextField(null=True)),
                ('schlafzimmer', models.TextField(null=True)),
                ('kinderzimmer', models.TextField(null=True)),
                ('abstellraum', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
                ('option_type', models.CharField(choices=[('', '-----select-----'), ('gw', 'Gewerk'), ('st', 'Status')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Choice_options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('choice_option', models.CharField(max_length=100)),
                ('choice_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('dach', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Elektro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('elektro', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Erdbau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('erdbau', models.TextField(null=True)),
                ('fundamentplan', models.FileField(null=True, upload_to='plan_pdf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estrich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('daemmplatten', models.TextField(null=True)),
                ('estrich', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fenster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('kellergeschoss', models.TextField(null=True)),
                ('erdgeschoss', models.TextField(null=True)),
                ('regelgeschoss', models.TextField(null=True)),
                ('dachgeschoss', models.TextField(null=True)),
                ('treppenhaus', models.TextField(null=True)),
                ('tiefgarage', models.TextField(null=True)),
                ('fensterbaenke', models.TextField(null=True)),
                ('rolllaeden', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fensterbanke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('treppenhaus', models.TextField(null=True)),
                ('wohnung', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fliesenleger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('treppenhaus', models.TextField(null=True)),
                ('bad', models.TextField(null=True)),
                ('wohnzimmer', models.TextField(null=True)),
                ('abstellraum', models.TextField(null=True)),
                ('esszimmer', models.TextField(null=True)),
                ('keller', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Handwerker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unternehmen', models.CharField(max_length=200)),
                ('anschrift', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Haus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haus_nr', models.CharField(max_length=2)),
                ('tiefgaragenbeschichtung', models.TextField(null=True)),
                ('trennwandsysteme', models.TextField(null=True)),
                ('klimatisierung', models.TextField(null=True)),
                ('architekt_plan', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Architekt_plan')),
                ('aufzug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteman.aufzug')),
                ('aussenanlagern', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Aussenanlagern')),
                ('aussenputz', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Aussenputz')),
                ('bodenbelaege', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Bodenbelaege')),
                ('dach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteman.Dach')),
                ('elektro', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Elektro')),
                ('erdbau', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteman.Erdbau')),
                ('estrich', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteman.Estrich')),
                ('fenster', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Fenster')),
                ('fliesenleger', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Fliesenleger')),
            ],
        ),
        migrations.CreateModel(
            name='Innenputz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('innenputz_bad', models.TextField(null=True)),
                ('innenputz_wohnraueme', models.TextField(null=True)),
                ('handwerker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Klimatisierung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('klimatisierung', models.TextField(null=True)),
                ('handwerker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('tapete', models.TextField(null=True)),
                ('farbe', models.TextField(null=True)),
                ('handwerker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt_name', models.CharField(max_length=200)),
                ('projekt_addresse', models.CharField(max_length=200)),
                ('projekt_stadt', models.CharField(max_length=50)),
                ('projekt_nutzungstyp', models.CharField(max_length=50)),
                ('projekt_anfangsdatum', models.DateField(null=True)),
                ('projekt_enddatum', models.DateField(null=True)),
                ('projekt_energetischer_standard', models.CharField(blank=True, max_length=20, null=True)),
                ('projekt_beschreibung', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raumbuch_elektro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('bad', models.TextField(null=True)),
                ('kueche', models.TextField(null=True)),
                ('flur', models.TextField(null=True)),
                ('wohnzimmer', models.TextField(null=True)),
                ('gaeste_wc', models.TextField(null=True)),
                ('schlafzimmer', models.TextField(null=True)),
                ('kinderzimmer', models.TextField(null=True)),
                ('abstellraum', models.TextField(null=True)),
                ('schalterprogramm', models.TextField(null=True)),
                ('tv_anschluss', models.TextField(null=True)),
                ('telefon_anschluss', models.TextField(null=True)),
                ('internet_anschluss', models.TextField(null=True)),
                ('handwerker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rohbau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('bodenplatte', models.TextField(null=True)),
                ('geschossdecken', models.TextField(null=True)),
                ('aussenwaende', models.TextField(null=True)),
                ('tiefgaragenrampe', models.TextField(null=True)),
                ('tragendewaende', models.TextField(null=True)),
                ('innenwaende', models.TextField(null=True)),
                ('nichttragendewaende', models.TextField(null=True)),
                ('dach', models.TextField(null=True)),
                ('treppen', models.TextField(null=True)),
                ('balkon', models.TextField(null=True)),
                ('handwerker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sanitaer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('aussenanschluss', models.TextField(null=True)),
                ('dusche', models.TextField(null=True)),
                ('badewanne', models.TextField(null=True)),
                ('waschbecken', models.TextField(null=True)),
                ('toilette', models.TextField(null=True)),
                ('waschmaschinenanschluss', models.TextField(null=True)),
                ('spuele', models.TextField(null=True)),
                ('spuelmaschinenanschluss', models.TextField(null=True)),
                ('fussbodenheizung', models.TextField(null=True)),
                ('handwerker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schliessanlage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('schliessplan', models.TextField(null=True)),
                ('innenbaenke', models.TextField(null=True)),
                ('handwerker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schlosser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('eingangstuer', models.TextField(null=True)),
                ('wohnungtuer', models.TextField(null=True)),
                ('innentueren', models.TextField(null=True)),
                ('handwerker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schreiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('haustuer', models.TextField(null=True)),
                ('wohnungstuer', models.TextField(null=True)),
                ('innentueren', models.TextField(null=True)),
                ('handwerker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sicherheitstechnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('alarmanlage', models.TextField(null=True)),
                ('tuerschliesser', models.TextField(null=True)),
                ('sicherheitsschloesser', models.TextField(null=True)),
                ('schliesssystem', models.TextField(null=True)),
                ('handwerker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trockenbau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
                ('waende', models.TextField(null=True)),
                ('decken', models.TextField(null=True)),
                ('handwerker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wohnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wohnung_nr', models.CharField(max_length=20)),
                ('bodenbelaege', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Bodenbelaege')),
                ('elektro', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Elektro')),
                ('estrich', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteman.Estrich')),
                ('fenster', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Fenster')),
                ('fliesenleger', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Fliesenleger')),
                ('haus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus')),
                ('maler', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Maler')),
                ('raumbuch_elektro', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Raumbuch_elektro')),
                ('sanitaer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Sanitaer')),
                ('schliessanlage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Schliessanlage')),
                ('schlosser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Schlosser')),
                ('schreiner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Schreiner')),
                ('sicherheitstechnik', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Sicherheitstechnik')),
                ('trockenbau', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Trockenbau')),
            ],
        ),
        migrations.AddField(
            model_name='haus',
            name='innenputz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteman.Innenputz'),
        ),
        migrations.AddField(
            model_name='haus',
            name='maler',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteman.Maler'),
        ),
        migrations.AddField(
            model_name='haus',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteman.Projekt'),
        ),
        migrations.AddField(
            model_name='haus',
            name='rohbau',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Rohbau'),
        ),
        migrations.AddField(
            model_name='haus',
            name='sanitaer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Sanitaer'),
        ),
        migrations.AddField(
            model_name='haus',
            name='schliessanlage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Schliessanlage'),
        ),
        migrations.AddField(
            model_name='haus',
            name='schlosser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Schlosser'),
        ),
        migrations.AddField(
            model_name='haus',
            name='schreiner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Schreiner'),
        ),
        migrations.AddField(
            model_name='haus',
            name='sicherheitstechnik',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Sicherheitstechnik'),
        ),
        migrations.AddField(
            model_name='haus',
            name='trockenbau',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Trockenbau'),
        ),
        migrations.AddField(
            model_name='fliesenleger',
            name='handwerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker'),
        ),
        migrations.AddField(
            model_name='fensterbanke',
            name='handwerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker'),
        ),
        migrations.AddField(
            model_name='fenster',
            name='handwerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker'),
        ),
        migrations.AddField(
            model_name='estrich',
            name='handwerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker'),
        ),
        migrations.AddField(
            model_name='erdbau',
            name='handwerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker'),
        ),
        migrations.AddField(
            model_name='elektro',
            name='handwerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker'),
        ),
        migrations.AddField(
            model_name='dach',
            name='handwerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker'),
        ),
        migrations.AddField(
            model_name='choice_options',
            name='handwerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker'),
        ),
        migrations.AddField(
            model_name='bodenbelaege',
            name='handwerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker'),
        ),
        migrations.AddField(
            model_name='aussenputz',
            name='handwerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker'),
        ),
        migrations.AddField(
            model_name='aussenanlagern',
            name='handwerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker'),
        ),
        migrations.AddField(
            model_name='aufzug',
            name='handwerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Handwerker'),
        ),
    ]
