# Generated by Django 2.1.5 on 2019-02-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architekt_plan',
            name='abstandsflaechenplan',
            field=models.FileField(blank=True, null=True, upload_to='plan_pdf/'),
        ),
        migrations.AlterField(
            model_name='architekt_plan',
            name='ansichten_plan',
            field=models.FileField(blank=True, null=True, upload_to='plan_pdf'),
        ),
        migrations.AlterField(
            model_name='architekt_plan',
            name='brandschutzkonzept',
            field=models.FileField(blank=True, null=True, upload_to='plan_pdf'),
        ),
        migrations.AlterField(
            model_name='architekt_plan',
            name='energieausweis',
            field=models.FileField(blank=True, null=True, upload_to='plan_pdf'),
        ),
        migrations.AlterField(
            model_name='architekt_plan',
            name='freiflaechenplan',
            field=models.FileField(blank=True, null=True, upload_to='plan_pdf'),
        ),
        migrations.AlterField(
            model_name='architekt_plan',
            name='statik_plan',
            field=models.FileField(blank=True, null=True, upload_to='plan_pdf'),
        ),
        migrations.AlterField(
            model_name='aufzug',
            name='aufzug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aussenanlagern',
            name='pflanzen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aussenanlagern',
            name='pflaster',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aussenanlagern',
            name='terrassenbelaege',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aussenputz',
            name='aussenputz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aussenputz',
            name='sockel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodenbelaege',
            name='abstellraum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodenbelaege',
            name='bad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodenbelaege',
            name='flur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodenbelaege',
            name='gaeste_wc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodenbelaege',
            name='kinderzimmer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodenbelaege',
            name='kueche',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodenbelaege',
            name='schlafzimmer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodenbelaege',
            name='tiefgarage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodenbelaege',
            name='treppenhaus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodenbelaege',
            name='wohnzimmer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choice_options',
            name='choice_option',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='choice_options',
            name='choice_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dach',
            name='dach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elektro',
            name='elektro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='erdbau',
            name='erdbau',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='erdbau',
            name='fundamentplan',
            field=models.FileField(blank=True, null=True, upload_to='plan_pdf'),
        ),
        migrations.AlterField(
            model_name='estrich',
            name='daemmplatten',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estrich',
            name='estrich',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fenster',
            name='dachgeschoss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fenster',
            name='erdgeschoss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fenster',
            name='fensterbaenke',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fenster',
            name='kellergeschoss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fenster',
            name='regelgeschoss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fenster',
            name='rolllaeden',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fenster',
            name='tiefgarage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fenster',
            name='treppenhaus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fensterbanke',
            name='treppenhaus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fensterbanke',
            name='wohnung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fliesenleger',
            name='abstellraum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fliesenleger',
            name='bad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fliesenleger',
            name='esszimmer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fliesenleger',
            name='keller',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fliesenleger',
            name='treppenhaus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fliesenleger',
            name='wohnzimmer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handwerker',
            name='anschrift',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='handwerker',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='handwerker',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='haus',
            name='architekt_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Architekt_plan'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='aufzug',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.aufzug'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='aussenanlagern',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Aussenanlagern'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='aussenputz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Aussenputz'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='bodenbelaege',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Bodenbelaege'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='dach',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Dach'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='elektro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Elektro'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='erdbau',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Erdbau'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='estrich',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Estrich'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='fenster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Fenster'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='fliesenleger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Fliesenleger'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='innenputz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Innenputz'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='klimatisierung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='haus',
            name='maler',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Maler'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='rohbau',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Rohbau'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='sanitaer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Sanitaer'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='schliessanlage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Schliessanlage'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='schlosser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Schlosser'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='schreiner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Schreiner'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='sicherheitstechnik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Sicherheitstechnik'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='tiefgaragenbeschichtung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='haus',
            name='trennwandsysteme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='haus',
            name='trockenbau',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Trockenbau'),
        ),
        migrations.AlterField(
            model_name='innenputz',
            name='innenputz_bad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='innenputz',
            name='innenputz_wohnraueme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='klimatisierung',
            name='klimatisierung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maler',
            name='farbe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maler',
            name='tapete',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='projekt_addresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='projekt_anfangsdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='projekt_beschreibung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='projekt_enddatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='projekt_nutzungstyp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='projekt_stadt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raumbuch_elektro',
            name='abstellraum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raumbuch_elektro',
            name='bad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raumbuch_elektro',
            name='flur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raumbuch_elektro',
            name='gaeste_wc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raumbuch_elektro',
            name='internet_anschluss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raumbuch_elektro',
            name='kinderzimmer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raumbuch_elektro',
            name='kueche',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raumbuch_elektro',
            name='schalterprogramm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raumbuch_elektro',
            name='schlafzimmer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raumbuch_elektro',
            name='telefon_anschluss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raumbuch_elektro',
            name='tv_anschluss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raumbuch_elektro',
            name='wohnzimmer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rohbau',
            name='aussenwaende',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rohbau',
            name='balkon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rohbau',
            name='bodenplatte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rohbau',
            name='dach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rohbau',
            name='geschossdecken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rohbau',
            name='innenwaende',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rohbau',
            name='nichttragendewaende',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rohbau',
            name='tiefgaragenrampe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rohbau',
            name='tragendewaende',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rohbau',
            name='treppen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanitaer',
            name='aussenanschluss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanitaer',
            name='badewanne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanitaer',
            name='dusche',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanitaer',
            name='fussbodenheizung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanitaer',
            name='spuele',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanitaer',
            name='spuelmaschinenanschluss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanitaer',
            name='toilette',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanitaer',
            name='waschbecken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanitaer',
            name='waschmaschinenanschluss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schliessanlage',
            name='innenbaenke',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schliessanlage',
            name='schliessplan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schlosser',
            name='eingangstuer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schlosser',
            name='innentueren',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schlosser',
            name='wohnungtuer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schreiner',
            name='haustuer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schreiner',
            name='innentueren',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schreiner',
            name='wohnungstuer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sicherheitstechnik',
            name='alarmanlage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sicherheitstechnik',
            name='schliesssystem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sicherheitstechnik',
            name='sicherheitsschloesser',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sicherheitstechnik',
            name='tuerschliesser',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trockenbau',
            name='decken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trockenbau',
            name='waende',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wohnung',
            name='bodenbelaege',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Bodenbelaege'),
        ),
        migrations.AlterField(
            model_name='wohnung',
            name='elektro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Elektro'),
        ),
        migrations.AlterField(
            model_name='wohnung',
            name='estrich',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Estrich'),
        ),
        migrations.AlterField(
            model_name='wohnung',
            name='fenster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Fenster'),
        ),
        migrations.AlterField(
            model_name='wohnung',
            name='fliesenleger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Fliesenleger'),
        ),
        migrations.AlterField(
            model_name='wohnung',
            name='maler',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Maler'),
        ),
        migrations.AlterField(
            model_name='wohnung',
            name='raumbuch_elektro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Raumbuch_elektro'),
        ),
        migrations.AlterField(
            model_name='wohnung',
            name='sanitaer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Sanitaer'),
        ),
        migrations.AlterField(
            model_name='wohnung',
            name='schliessanlage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Schliessanlage'),
        ),
        migrations.AlterField(
            model_name='wohnung',
            name='schlosser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Schlosser'),
        ),
        migrations.AlterField(
            model_name='wohnung',
            name='schreiner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Schreiner'),
        ),
        migrations.AlterField(
            model_name='wohnung',
            name='sicherheitstechnik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Sicherheitstechnik'),
        ),
        migrations.AlterField(
            model_name='wohnung',
            name='trockenbau',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Trockenbau'),
        ),
    ]
