# Generated by Django 2.1.5 on 2019-02-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0002_auto_20190225_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufzug',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='aussenanlagern',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='aussenputz',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='bodenbelaege',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='choice_options',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='dach',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='elektro',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='erdbau',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='estrich',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='fenster',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='fensterbanke',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='fliesenleger',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='innenputz',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='klimatisierung',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='maler',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='raumbuch_elektro',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='rohbau',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='sanitaer',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='schliessanlage',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='schlosser',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='schreiner',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='sicherheitstechnik',
            name='handwerker',
        ),
        migrations.RemoveField(
            model_name='trockenbau',
            name='handwerker',
        ),
        migrations.AlterField(
            model_name='haus',
            name='haus_nr',
            field=models.CharField(max_length=10),
        ),
    ]
