# Generated by Django 2.1.5 on 2019-02-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0003_auto_20190225_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufzug',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='aussenanlagern',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='aussenputz',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='bodenbelaege',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='choice_options',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='dach',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='elektro',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='erdbau',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='estrich',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='fenster',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='fensterbanke',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='fliesenleger',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='innenputz',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='klimatisierung',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='maler',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='raumbuch_elektro',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='rohbau',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='sanitaer',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='schliessanlage',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='schlosser',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='schreiner',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='sicherheitstechnik',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='trockenbau',
            name='status',
            field=models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2),
        ),
    ]
