# Generated by Django 2.1.5 on 2019-02-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0004_auto_20190225_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='aussenanlagern',
            name='grundfladhe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aussenanlagern',
            name='wegeflachen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
