# Generated by Django 2.1.5 on 2019-02-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0006_auto_20190225_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='aussenanlagern',
            name='einfriedung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aussenanlagern',
            name='mulleinhausung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
