# Generated by Django 2.1.5 on 2019-02-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0008_auto_20190226_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='projekt_status',
            field=models.BooleanField(default=True),
        ),
    ]
