# Generated by Django 2.1.5 on 2019-02-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0009_projekt_projekt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='haus',
            name='display_nr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
