# Generated by Django 2.1.5 on 2019-03-01 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0011_auto_20190301_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fensterbanke',
        ),
        migrations.DeleteModel(
            name='Klimatisierung',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='architekt_plan',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='aussenanlagern',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='aussenputz',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='bodenbelaege',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='dach',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='elektro',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='erdbau',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='estrich',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='fenster',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='fliesenleger',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='innenputz',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='maler',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='rohbau',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='sanitaer',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='schliessanlage',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='schlosser',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='schreiner',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='sicherheitstechnik',
        ),
        migrations.RemoveField(
            model_name='haus',
            name='trockenbau',
        ),
        migrations.RemoveField(
            model_name='wohnung',
            name='bodenbelaege',
        ),
        migrations.RemoveField(
            model_name='wohnung',
            name='elektro',
        ),
        migrations.RemoveField(
            model_name='wohnung',
            name='estrich',
        ),
        migrations.RemoveField(
            model_name='wohnung',
            name='fenster',
        ),
        migrations.RemoveField(
            model_name='wohnung',
            name='fliesenleger',
        ),
        migrations.RemoveField(
            model_name='wohnung',
            name='maler',
        ),
        migrations.RemoveField(
            model_name='wohnung',
            name='raumbuch_elektro',
        ),
        migrations.RemoveField(
            model_name='wohnung',
            name='sanitaer',
        ),
        migrations.RemoveField(
            model_name='wohnung',
            name='schliessanlage',
        ),
        migrations.RemoveField(
            model_name='wohnung',
            name='schlosser',
        ),
        migrations.RemoveField(
            model_name='wohnung',
            name='schreiner',
        ),
        migrations.RemoveField(
            model_name='wohnung',
            name='sicherheitstechnik',
        ),
        migrations.RemoveField(
            model_name='wohnung',
            name='trockenbau',
        ),
        migrations.AddField(
            model_name='architekt_plan',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='aussenanlagern',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='aussenputz',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='bodenbelaege',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='bodenbelaege',
            name='wohnung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung'),
        ),
        migrations.AddField(
            model_name='dach',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='elektro',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='elektro',
            name='wohnung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung'),
        ),
        migrations.AddField(
            model_name='erdbau',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='estrich',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='estrich',
            name='wohnung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung'),
        ),
        migrations.AddField(
            model_name='fenster',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='fenster',
            name='wohnung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung'),
        ),
        migrations.AddField(
            model_name='fliesenleger',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='fliesenleger',
            name='wohnung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung'),
        ),
        migrations.AddField(
            model_name='innenputz',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='innenputz',
            name='wohnung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung'),
        ),
        migrations.AddField(
            model_name='maler',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='maler',
            name='wohnung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung'),
        ),
        migrations.AddField(
            model_name='raumbuch_elektro',
            name='wohnung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung'),
        ),
        migrations.AddField(
            model_name='rohbau',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='sanitaer',
            name='wohnung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung'),
        ),
        migrations.AddField(
            model_name='schliessanlage',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='schliessanlage',
            name='wohnung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung'),
        ),
        migrations.AddField(
            model_name='schlosser',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='schlosser',
            name='wohnung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung'),
        ),
        migrations.AddField(
            model_name='schreiner',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='schreiner',
            name='wohnung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung'),
        ),
        migrations.AddField(
            model_name='sicherheitstechnik',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='sicherheitstechnik',
            name='wohnung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung'),
        ),
        migrations.AddField(
            model_name='trockenbau',
            name='haus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus'),
        ),
        migrations.AddField(
            model_name='trockenbau',
            name='wohnung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung'),
        ),
        migrations.AlterField(
            model_name='haus',
            name='aufzug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='aufzug',
        ),
    ]
