# Generated by Django 2.1.5 on 2019-03-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0012_auto_20190301_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanitaer',
            old_name='aussenanschluss',
            new_name='aussenzapfstelle',
        ),
    ]
