# Generated by Django 2.1.5 on 2019-03-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0014_architekt_plan_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rohbau',
            old_name='aussenwaende',
            new_name='aussenwande',
        ),
        migrations.RenameField(
            model_name='rohbau',
            old_name='innenwaende',
            new_name='innenwande',
        ),
        migrations.RenameField(
            model_name='rohbau',
            old_name='nichttragendewaende',
            new_name='nichttragendewande',
        ),
        migrations.RenameField(
            model_name='rohbau',
            old_name='tragendewaende',
            new_name='tragendewande',
        ),
        migrations.RenameField(
            model_name='trockenbau',
            old_name='waende',
            new_name='wande',
        ),
    ]
