# Generated by Django 2.1.5 on 2019-03-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0017_auto_20190306_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanitaer',
            old_name='abwasserung',
            new_name='entwasserung',
        ),
    ]
