# Generated by Django 2.1.5 on 2019-03-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0018_auto_20190307_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rohbau',
            old_name='innenwande',
            new_name='nichttragendeinnenwande',
        ),
        migrations.RenameField(
            model_name='rohbau',
            old_name='nichttragendewande',
            new_name='tragendeinnenwande',
        ),
        migrations.RemoveField(
            model_name='rohbau',
            name='tragendewande',
        ),
    ]
