# Generated by Django 2.1.5 on 2019-03-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0019_auto_20190307_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicherheitstechnik',
            name='schliesssystem',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf'),
        ),
    ]
