# Generated by Django 2.1.5 on 2019-03-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0020_auto_20190311_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sicherheitstechnik',
            name='schliesssystem',
        ),
    ]
