# Generated by Django 2.1.5 on 2019-03-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0021_remove_sicherheitstechnik_schliesssystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sicherheitstechnik',
            name='schliesssystem',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf'),
        ),
    ]
