# Generated by Django 2.1.5 on 2019-03-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0022_sicherheitstechnik_schliesssystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wohnung',
            name='clients_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='wohnung',
            name='clients_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wohnung',
            name='clients_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wohnung',
            name='clients_tel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
