# Generated by Django 2.1.5 on 2019-03-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0023_auto_20190312_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='rohbau',
            name='grundung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
