# Generated by Django 2.1.5 on 2019-03-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0025_auto_20190313_1057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice_fields',
            new_name='ChoiceFields',
        ),
    ]
