# Generated by Django 2.1.5 on 2019-03-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0026_auto_20190313_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicefields',
            name='display',
            field=models.CharField(default='--select--', max_length=50),
        ),
        migrations.AlterField(
            model_name='choicefields',
            name='option',
            field=models.CharField(default='sl', max_length=5),
        ),
        migrations.AlterField(
            model_name='choicefields',
            name='option_type',
            field=models.CharField(choices=[('sl', '--select--'), ('gw', 'gewerk'), ('st', 'status'), ('gr', 'grundung')], max_length=50),
        ),
    ]
