# Generated by Django 2.1.5 on 2019-03-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0027_auto_20190313_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rohbau',
            old_name='aussenwande',
            new_name='aussenwande_kellergeschoss',
        ),
    ]
