# Generated by Django 2.1.5 on 2019-03-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0028_auto_20190313_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='rohbau',
            name='aussenwande_eg_og_dg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
