# Generated by Django 2.1.5 on 2019-03-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0029_rohbau_aussenwande_eg_og_dg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicefields',
            options={'ordering': ['option_type']},
        ),
        migrations.AddField(
            model_name='rohbau',
            name='installationschachte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choicefields',
            name='option_type',
            field=models.CharField(choices=[('sl', '--select--'), ('gw', 'gewerk'), ('st', 'status'), ('gr', 'grundung'), ('aw_eg_og_dg', 'aussenwande_eg_og_dg')], max_length=50),
        ),
    ]
