# Generated by Django 2.1.5 on 2019-03-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0031_auto_20190313_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dach',
            name='flchdach_stahlbeton',
        ),
        migrations.RemoveField(
            model_name='dach',
            name='zeigeldach',
        ),
        migrations.AlterField(
            model_name='choicefields',
            name='option_type',
            field=models.CharField(choices=[('sl', '--select--'), ('gw', 'gewerk'), ('st', 'status'), ('gr', 'grundung'), ('aw_eg_og_dg', 'aussenwande_eg_og_dg'), ('dach', 'dach')], max_length=50),
        ),
    ]
