# Generated by Django 2.1.5 on 2019-03-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0032_auto_20190313_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenster',
            name='algemeine_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
