# Generated by Django 2.1.5 on 2019-03-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0038_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='components',
            field=models.CharField(choices=[('ar', 'Architeckt'), ('eb', 'Erdbau'), ('rb', 'Rohbau'), ('fen', 'Fenster'), ('elek', 'Elektro'), ('sani', 'Sanitar'), ('flie', 'Fliesenleger'), ('boden', 'Bodenbelaege'), ('turen', 'Turen'), ('sanl', 'Schliessanlage'), ('aanl', 'Aussenanlage')], max_length=50),
        ),
    ]
