# Generated by Django 2.1.5 on 2019-03-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0039_auto_20190326_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='WohnungPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('components', models.CharField(choices=[('ar', 'Architeckt'), ('eb', 'Erdbau'), ('rb', 'Rohbau'), ('fen', 'Fenster'), ('elek', 'Elektro'), ('sani', 'Sanitar'), ('flie', 'Fliesenleger'), ('boden', 'Bodenbelaege'), ('turen', 'Turen'), ('sanl', 'Schliessanlage'), ('aanl', 'Aussenanlage')], max_length=50)),
                ('plan', models.FileField(blank=True, null=True, upload_to='plan_pdf/')),
                ('wohnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung')),
            ],
        ),
    ]
