# Generated by Django 2.1.5 on 2019-04-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0041_auto_20190402_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='elektro',
            name='freiflachen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elektro',
            name='keller',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elektro',
            name='medientechnik',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elektro',
            name='private_abstellraum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elektro',
            name='tiefgarage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elektro',
            name='treppenhaus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
