# Generated by Django 2.1.5 on 2019-04-03 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0042_auto_20190403_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fenster',
            name='algemeine_information',
        ),
    ]
