# Generated by Django 2.1.5 on 2019-04-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0044_auto_20190403_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2)),
                ('energiegwinnung', models.TextField(blank=True, null=True)),
                ('heizung', models.TextField(blank=True, null=True)),
                ('be_und_entluftung', models.TextField(blank=True, null=True)),
                ('verbauchserfassung', models.TextField(blank=True, null=True)),
                ('klimatisierung', models.TextField(blank=True, null=True)),
                ('kalt_und_warmwasser', models.TextField(blank=True, null=True)),
                ('zirkulationsleitung', models.TextField(blank=True, null=True)),
                ('entwasserung', models.TextField(blank=True, null=True)),
                ('wasserenthartung', models.TextField(blank=True, null=True)),
                ('sonstiges', models.TextField(blank=True, null=True)),
                ('haus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus')),
                ('wohnung', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
