# Generated by Django 2.1.5 on 2019-04-03 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0045_hls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanitaer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2)),
                ('heizung', models.TextField(blank=True, null=True)),
                ('entwasserung', models.TextField(blank=True, null=True)),
                ('aussenzapfstelle', models.TextField(blank=True, null=True)),
                ('dusche', models.TextField(blank=True, null=True)),
                ('badewanne', models.TextField(blank=True, null=True)),
                ('waschbecken', models.TextField(blank=True, null=True)),
                ('toilette', models.TextField(blank=True, null=True)),
                ('waschmaschinenanschluss', models.TextField(blank=True, null=True)),
                ('spuele', models.TextField(blank=True, null=True)),
                ('spuelmaschinenanschluss', models.TextField(blank=True, null=True)),
                ('fussbodenheizung', models.TextField(blank=True, null=True)),
                ('sonstiges', models.TextField(blank=True, null=True)),
                ('haus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus')),
                ('wohnung', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
