# Generated by Django 2.1.5 on 2019-04-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0048_auto_20190403_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrich',
            name='bader',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estrich',
            name='wohnraume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
