# Generated by Django 2.1.5 on 2019-04-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0049_auto_20190403_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='trockenbau',
            name='installationsschachte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trockenbau',
            name='vorsatzschalen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
