# Generated by Django 2.1.5 on 2019-04-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0050_auto_20190403_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aussenputz',
            name='aussenputz',
        ),
    ]
