# Generated by Django 2.1.5 on 2019-04-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0051_remove_aussenputz_aussenputz'),
    ]

    operations = [
        migrations.AddField(
            model_name='aussenputz',
            name='edelputz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aussenputz',
            name='unterputz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
