# Generated by Django 2.1.5 on 2019-04-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0052_auto_20190403_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodenbelaege',
            name='keller',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodenbelaege',
            name='technikraum',
            field=models.TextField(blank=True, null=True),
        ),
    ]
