# Generated by Django 2.1.5 on 2019-04-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0053_auto_20190403_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schreiner',
            name='haus',
        ),
        migrations.RemoveField(
            model_name='schreiner',
            name='wohnung',
        ),
        migrations.DeleteModel(
            name='Schreiner',
        ),
    ]
