# Generated by Django 2.1.5 on 2019-04-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0054_auto_20190403_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='turen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ns', 'Not yet started'), ('ru', 'Running'), ('co', 'Completed')], default='ns', max_length=2)),
                ('haustuer', models.TextField(blank=True, null=True)),
                ('brandschutzturen', models.TextField(blank=True, null=True)),
                ('schleusenturen', models.TextField(blank=True, null=True)),
                ('kellerflurturen', models.TextField(blank=True, null=True)),
                ('sonstiges', models.TextField(blank=True, null=True)),
                ('haus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Haus')),
                ('wohnung', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteman.Wohnung')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
