# Generated by Django 2.1.5 on 2019-04-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0056_auto_20190403_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='schlosser',
            name='absturzsicherungen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schlosser',
            name='balkongelander',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schlosser',
            name='kellerabtrennungen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schlosser',
            name='rollgittertor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schlosser',
            name='treppenglander',
            field=models.TextField(blank=True, null=True),
        ),
    ]
