# Generated by Django 2.1.5 on 2019-04-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0057_auto_20190403_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sicherheitstechnik',
            old_name='tuerschliesser',
            new_name='videouberwachung',
        ),
        migrations.RemoveField(
            model_name='sicherheitstechnik',
            name='schliesssystem',
        ),
    ]
