# Generated by Django 2.1.5 on 2019-04-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0059_auto_20190403_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fenster',
            name='rolllaeden',
        ),
        migrations.AddField(
            model_name='fenster',
            name='schwellen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fenster',
            name='sichtschutz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='components',
            field=models.CharField(choices=[('ar', 'Architeckt'), ('gp', 'Gesamtplanung'), ('eb', 'Erdbau'), ('rb', 'Rohbau'), ('fen', 'Fenster'), ('elek', 'Elektro'), ('sani', 'Sanitar'), ('flie', 'Fliesenleger'), ('boden', 'Bodenbelaege'), ('turen', 'Turen'), ('sanl', 'Schliessanlage'), ('aanl', 'Aussenanlage')], max_length=50),
        ),
    ]
