# Generated by Django 2.1.5 on 2019-04-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0060_auto_20190403_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='elektro',
            name='allgemein',
            field=models.TextField(blank=True, null=True),
        ),
    ]
