# Generated by Django 2.1.5 on 2019-04-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0061_elektro_allgemein'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitaer',
            name='heizkorper',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanitaer',
            name='waschtisch_im_bad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanitaer',
            name='waschtisch_im_duschbad_wc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
