# Generated by Django 2.1.5 on 2019-04-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0062_auto_20190403_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanitaer',
            name='spuele',
        ),
        migrations.RemoveField(
            model_name='sanitaer',
            name='waschbecken',
        ),
    ]
