# Generated by Django 2.1.5 on 2019-04-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0064_auto_20190403_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrich',
            name='fussbodenaufbau_bad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estrich',
            name='fussbodenaufbau_wohnraume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
