# Generated by Django 2.1.5 on 2019-04-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0065_auto_20190403_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='turen',
            name='innenturen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turen',
            name='wohnungstur',
            field=models.TextField(blank=True, null=True),
        ),
    ]
