# Generated by Django 2.1.5 on 2019-04-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0067_auto_20190403_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='innenputz',
            name='edelputz_bad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='innenputz',
            name='edelputz_wohnraume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
