# Generated by Django 2.1.5 on 2019-04-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0068_auto_20190403_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenster',
            name='keller',
            field=models.TextField(blank=True, null=True),
        ),
    ]
