# Generated by Django 2.1.5 on 2019-04-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0069_fenster_keller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanitaer',
            name='entwasserung',
        ),
        migrations.RemoveField(
            model_name='sanitaer',
            name='fussbodenheizung',
        ),
        migrations.RemoveField(
            model_name='sanitaer',
            name='heizung',
        ),
    ]
