# Generated by Django 2.1.5 on 2019-04-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0070_auto_20190408_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raumbuch_elektro',
            name='internet_anschluss',
        ),
        migrations.RemoveField(
            model_name='raumbuch_elektro',
            name='telefon_anschluss',
        ),
        migrations.RemoveField(
            model_name='raumbuch_elektro',
            name='tv_anschluss',
        ),
    ]
