# Generated by Django 2.1.5 on 2019-04-09 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0072_auto_20190409_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wohnungplan',
            name='plan',
            field=models.FileField(null=True, upload_to='wohnung/plan_pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])]),
        ),
    ]
