# Generated by Django 2.1.5 on 2019-04-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteman', '0073_auto_20190409_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwerker',
            name='gewerk_type',
            field=models.CharField(default='default_gewerk', max_length=20),
        ),
        migrations.AlterField(
            model_name='choicefields',
            name='option',
            field=models.CharField(default='sl', max_length=20, unique=True),
        ),
    ]
